apiVersion: bobbycar.redhat.com/v1alpha1
kind: BobbycarZone
metadata:
  name: de-ffm-env
spec:
  name: "Frankfurt Environmental Zone"
  type: "circle"
  priority: 10
  position:
    lat: 50.1146997
    lng: 8.6185411
  radius: 5000  