kind: Service
apiVersion: v1
metadata:
  name: cache-service
  labels:
    camel.apache.org/generation: '1'
    camel.apache.org/integration: cache-service
    camel.apache.org/service.type: user
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    camel.apache.org/integration: cache-service
  type: ClusterIP
  sessionAffinity: None