apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-zones
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - bobbycar.redhat.com
    resources:
      - '*'