apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: k8s
  name: car-simulator-service-monitor
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: 8080-tcp
      scheme: http
  namespaceSelector:
    matchNames:
      - bobbycar
  selector:
    matchLabels:
      app: car-simulator
