kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  labels:
    app: car-simulator
  name: ubi-quarkus-native-s2i
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 19.3.1-java11
      from:
        kind: DockerImage
        name: 'quay.io/quarkus/ubi-quarkus-native-s2i:19.3.1-java11'
      importPolicy: {}
      referencePolicy:
        type: Source