kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bobbycar-view-default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: bobbycar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-zones