kind: Secret
apiVersion: v1
metadata:
  name: datagrid2rest
stringData:
  application.properties: |-
    com.redhat.bobbycar.camelk.dg.car.cacheName: cars
    com.redhat.bobbycar.camelk.dg.zone.cacheName: zones
    com.redhat.bobbycar.camelk.dg.host: bobbycar-dg.camelk-test.svc.cluster.local
    com.redhat.bobbycar.camelk.dg.password: replace
    com.redhat.bobbycar.camelk.dg.user: replace
type: Opaque


